import type {EventItem} from './types';
export type EventTheme = 'music'|'business'|'cinema'|'theatre'|'ideas'|'night';
export function themeFor(category:string):EventTheme {const c=category.toLowerCase();if(/cinema|кино/.test(c))return 'cinema';if(/theat|ballet|театр|балет/.test(c))return 'theatre';if(/night|party|disco|вечерин/.test(c))return 'night';if(/business|network|founder|бизнес|знаком/.test(c))return 'business';if(/\bai\b|tech|research|lecture|лекц|технолог/.test(c))return 'ideas';return 'music';}
const categoryNames:Record<string,string>={
 'afterparty':'Афтепати','ai/technology/research conference':'Конференции по ИИ','business_networking':'Бизнес и знакомства',
 'cis/russian party':'Русскоязычные вечеринки','cis/fashion party':'Модные вечеринки сообществ','champions league football':'Лига чемпионов',
 'gt4/gt3/prototypes/historic':'Автогонки и исторические автомобили','halloween/house':'Хэллоуин и хаус','lamborghini/motorsport':'Ламборгини и автоспорт',
 'networking':'Знакомства и встречи','ru business/forum':'Русскоязычные бизнес-форумы','ru satire/talk/show':'Русскоязычные разговорные шоу',
 'business/networking':'Деловые знакомства','culture/music':'Музыка и культура','design/social':'Дизайн и встречи','electronic/nightlife':'Электронная музыка',
 'electronic/orchestral nightlife':'Электронная музыка и оркестр','endurance/motorsport':'Гонки на выносливость','executive/business/ai':'Бизнес, руководители и ИИ',
 'fashion':'Мода','fashion/culture':'Мода и культура','film/culture':'Кино и культура','football':'Футбол','motorsport/gt':'Автоспорт',
 'music':'Музыка','networking/business':'Деловые встречи','opera/social/dj':'Опера, встречи и диджеи','performing arts/festival':'Фестивали искусств',
 'running':'Бег','science/show':'Научные шоу','social/local festival':'Городские фестивали','tech/ai/engineering':'Технологии и инженерия'
};
export function categoryLabel(name:string):string {if(/[А-Яа-яЁё]/.test(name))return name.replace(/\bAI\b/gi,'ИИ');const c=name.toLowerCase();if(categoryNames[c])return categoryNames[c];if(/standup|comedy/.test(c))return 'Стендап';if(/ballet/.test(c))return 'Балет';if(/cinema|film/.test(c))return 'Кино';if(/theat/.test(c))return 'Театр';if(/tribute/.test(c))return 'Трибьют-концерт';if(/night|party|disco/.test(c))return 'Вечеринка';if(/business|executive|founder/.test(c))return 'Бизнес и знакомства';if(/network/.test(c))return 'Знакомства и встречи';if(/\bai\b|technology|research|tech|conference/.test(c))return 'Технологии и ИИ';if(/lecture/.test(c))return 'Лекция';if(/ukrainian.*pop/.test(c))return 'Украинская поп-музыка';if(/ukrainian.*rock/.test(c))return 'Украинский рок';if(/concert|music|pop|rock/.test(c))return 'Концерт';if(/show/.test(c))return 'Шоу';return 'Мероприятие';}
const cities:Record<string,string>={Milano:'Милан',Como:'Комо',Monza:'Монца',Lugano:'Лугано',Mendrisio:'Мендризио',Chiasso:'Кьяссо','Zürich':'Цюрих',Zurich:'Цюрих',Lecco:'Лекко',Massagno:'Массаньо','Lugano-Viganello':'Лугано, Виганелло',Pero:'Перо',Horgen:'Хорген','Dübendorf':'Дюбендорф'};
export function cityLabel(city:string|null){return city?cities[city]||city:'Город уточняется';}
const languages:Record<string,string>={ru:'Русский',en:'Английский',it:'Итальянский',uk:'Украинский',de:'Немецкий',fr:'Французский',be:'Белорусский',kk:'Казахский',ka:'Грузинский',hy:'Армянский',ro:'Румынский',es:'Испанский'};
export function languageLabel(code:string){return languages[code.toLowerCase()]||'Другой язык';}
export function eventCount(n:number){const a=n%100,b=n%10;return `${n} ${a>=11&&a<=14?'событий':b===1?'событие':b>=2&&b<=4?'события':'событий'}`;}
export function eventDate(e:EventItem){if(!e.starts_on)return 'Дата уточняется';const format=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('ru-RU',{day:'numeric',month:'long',timeZone:'UTC'});return format(e.starts_on)+(e.ends_on&&e.ends_on!==e.starts_on?' - '+format(e.ends_on):'')+(e.start_local?' · '+e.start_local.slice(0,5):'');}
export function priceLabel(e:EventItem){const t=e.tickets.find(x=>x.price_min!==null);if(!t)return 'Цена уточняется';if(Number(t.price_min)===0)return 'Бесплатно';return `От ${Number(t.price_min).toLocaleString('ru-RU')} ${t.currency==='EUR'?'€':t.currency==='CHF'?'фр.':t.currency||''}`;}
export function dateParts(date:string|null){if(!date)return {day:'?',month:'ДАТА'};const d=new Date(date+'T12:00:00Z');return {day:String(d.getUTCDate()).padStart(2,'0'),month:d.toLocaleDateString('ru-RU',{month:'short',timeZone:'UTC'}).replace('.','').toUpperCase()};}
export function todayInRome(now=new Date()){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
export function dateRange(preset:string,today:string){const a=new Date(today+'T12:00:00Z');const b=new Date(a);if(preset==='tomorrow'){a.setUTCDate(a.getUTCDate()+1);b.setUTCDate(b.getUTCDate()+1);}if(preset==='weekend'){const day=a.getUTCDay();const offset=day===0?-1:(6-day+7)%7;a.setUTCDate(a.getUTCDate()+offset);b.setTime(a.getTime());b.setUTCDate(a.getUTCDate()+1);}return {from:a.toISOString().slice(0,10),to:preset==='upcoming'?'':b.toISOString().slice(0,10)};}
