import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowLeft,ArrowUpRight,MapPin,CalendarDays,ShieldCheck,Ticket} from 'lucide-react';
import Brand from '@/components/Brand';
import EventArtwork from '@/components/EventArtwork';
import EventCard from '@/components/EventCard';
import {rpc} from '@/lib/rpc';
import {safeUrl} from '@/lib/filters';
import {categoryLabel,cityLabel,dateParts,eventDate,languageLabel,priceLabel,themeFor} from '@/lib/presentation';
import type {SearchResult} from '@/lib/types';
export const dynamic='force-dynamic';
export default async function EventPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;if(!/^[a-f\d-]{36}$/i.test(id))notFound();let result:SearchResult;
 try{result=await rpc<SearchResult>('radar_search',{p_filters:{occurrence_id:id,limit:1}});}catch{return <main id="main-content" className="not-found"><h1>Не удалось загрузить событие</h1><p>Пожалуйста, попробуйте открыть страницу позже.</p><Link className="primary-button" href="/">Вернуться к афише</Link></main>;}
 const e=result.items[0];if(!e)notFound();let related:SearchResult|null=null;
 try{related=await rpc<SearchResult>('radar_search',{p_filters:{city:e.city||undefined,category:e.categories[0]?.slug,from:e.starts_on,limit:7}});}catch{}
 const date=dateParts(e.starts_on);const firstTicket=e.tickets.map(t=>safeUrl(t.url)).find(Boolean);
 const description=e.description&&/[А-Яа-яЁё]/.test(e.description)?e.description.replaceAll('INVITE_ONLY','По приглашению'):'Подробнее о мероприятии: по ссылкам на источники ниже.';
 return <><header className="masthead"><div className="header-inner"><Brand/><Link className="location-button" href="/"><ArrowLeft size={15}/>К афише</Link></div></header><main id="main-content" className="detail"><Link href="/" className="back-link"><ArrowLeft size={16}/>Все мероприятия</Link>
 <section className="detail-hero"><div className="detail-art"><EventArtwork large theme={themeFor(e.categories[0]?.name||'')}/><div className="date-badge"><strong>{date.day}</strong><span>{date.month}</span></div></div><div className="detail-head"><span className="category">{categoryLabel(e.categories[0]?.name||'')}</span><h1>{e.title}</h1><p className="detail-date"><CalendarDays size={20}/>{eventDate(e)}</p><p className="place"><MapPin size={19}/>{cityLabel(e.city)} · {e.venue||'Место уточняется'}</p>{(e.normalized_address||e.original_address)&&<p className="detail-address">{e.normalized_address||e.original_address}</p>}<span className="verified"><ShieldCheck size={16}/>Источник подтверждён · Время местное</span></div></section>
 <div className="detail-columns"><section><h2>О событии</h2><p className="description">{description}</p><dl><dt>Язык</dt><dd>{e.languages.length?e.languages.map(languageLabel).join(', '):'Не указан'}</dd><dt>Артисты</dt><dd>{e.artists.map(a=>a.name).join(', ')||'Не указаны'}</dd><dt>Организатор</dt><dd>{e.organizers.map(a=>a.name).join(', ')||'Не указан'}</dd>{e.doors_local&&<><dt>Открытие дверей</dt><dd>{e.doors_local.slice(0,5)}</dd></>}<dt>Часовой пояс</dt><dd>{e.timezone||'Не указан'}</dd></dl><h2>Источники информации</h2><p className="verification">{e.last_verified?'Последняя проверка: '+new Date(e.last_verified).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric',timeZone:e.timezone||'UTC'}):'Время проверки не указано'}. Наличие билетов уточняется у продавца.</p><ul className="source-list">{e.sources.map((s,i)=>{const url=safeUrl(s.url);return url?<li key={i}><a href={url} rel="noopener noreferrer" target="_blank">{s.name}<ArrowUpRight size={15}/><span className="sr-only"> (откроется в новой вкладке)</span></a></li>:null;})}</ul></section>
 <aside className="ticket-panel" id="tickets"><p className="section-kicker">ТВОЙ СЛЕДУЮЩИЙ ВЕЧЕР</p><h2>{priceLabel(e)}</h2>{e.tickets.map((t,i)=>{const url=safeUrl(t.url);return url?<a className="primary-button" target="_blank" rel="noopener noreferrer" key={i} href={url}><Ticket size={17}/>Билеты{e.tickets.length>1?` · ${i+1}`:''}<ArrowUpRight size={17}/><span className="sr-only">: {t.provider||'продавец'}, новая вкладка</span></a>:null;})}{!firstTicket&&<p>Ссылка на билеты пока не указана. Проверьте источники.</p>}{(e.description?.includes('INVITE_ONLY')||e.membership)&&<p>Для входа может требоваться приглашение или подтверждение организатора.</p>}<p>Цена опубликована источником. Сборы могут оплачиваться отдельно.</p><p>Условия и наличие билетов проверяйте на сайте продавца.</p></aside></div>
 {related&&related.items.filter(x=>x.occurrence_id!==id).length>0&&<section className="related"><p className="section-kicker">ЕЩЁ ОДИН ПОВОД ВЫЙТИ</p><h2>Может понравиться</h2><div className="event-grid">{related.items.filter(x=>x.occurrence_id!==id).slice(0,6).map((x,i)=><EventCard key={x.occurrence_id} event={x} index={i}/>)}</div></section>}
 </main>{firstTicket&&<div className="mobile-ticket-cta"><span>{priceLabel(e)}</span><a className="primary-button" href={firstTicket} rel="noopener noreferrer" target="_blank">Билеты <ArrowUpRight size={17}/></a></div>}</>;
}
