'use client';
import {useEffect,useRef,useState} from 'react';import type {EventItem} from '@/lib/types';import {eventDate} from './EventCard';
import 'leaflet/dist/leaflet.css';
export default function EventMap({events,location,onBounds}:{events:EventItem[];location:{lat:number;lng:number}|null;onBounds:(bbox:string)=>void}){
 const host=useRef<HTMLDivElement>(null);const mapRef=useRef<import('leaflet').Map|null>(null);const layer=useRef<import('leaflet').LayerGroup|null>(null);const [failed,setFailed]=useState(false);
 useEffect(()=>{let cancelled=false;import('leaflet').then(L=>{if(cancelled||!host.current)return;const map=L.map(host.current,{zoomControl:true}).setView([46.25,8.95],7);mapRef.current=map;layer.current=L.layerGroup().addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(map);map.invalidateSize();}).catch(()=>setFailed(true));return()=>{cancelled=true;mapRef.current?.remove();mapRef.current=null;layer.current=null;};},[]);
 useEffect(()=>{let cancelled=false;import('leaflet').then(L=>{if(cancelled)return;const map=mapRef.current;const group=layer.current;if(!map||!group)return;group.clearLayers();for(const e of events){if(e.latitude===null||e.longitude===null||e.geocoding_status!=='VERIFIED')continue;const content=document.createElement('div');const link=document.createElement('a');link.href='/events/'+e.occurrence_id;link.textContent=e.title;content.append(link);const date=document.createElement('p');date.textContent=eventDate(e);content.append(date);L.circleMarker([e.latitude,e.longitude],{radius:9,color:'#142524',weight:2,fillColor:'#bafa5a',fillOpacity:1}).bindPopup(content).addTo(group);}if(location){L.circleMarker([location.lat,location.lng],{radius:7,color:'#fff',weight:3,fillColor:'#335de8',fillOpacity:1}).bindPopup('Ваше местоположение').addTo(group);map.setView([location.lat,location.lng],10);}});return()=>{cancelled=true;};},[events,location]);
 return <div className="map-shell"><div ref={host} className="map-canvas" aria-label="Карта мероприятий"/>{failed&&<div className="map-message">Не удалось загрузить карту.</div>}<button className="bounds-button" onClick={()=>{const b=mapRef.current?.getBounds();if(b)onBounds([b.getWest(),b.getSouth(),b.getEast(),b.getNorth()].join(','));}}>Искать в этой области</button><p className="map-caption">На карте — только места с проверенными координатами.</p></div>;
}
