'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {Search,LocateFixed,List,Map as MapIcon,SlidersHorizontal,RefreshCw,X,ArrowUpRight,ArrowDown,MapPin,ShieldCheck,ChevronDown,Sparkles,Ticket,Music2,UsersRound,Film,Drama,Cpu,Moon} from 'lucide-react';
import Brand from './Brand';
import EventCard from './EventCard';
import {categoryLabel,cityLabel,dateRange,eventCount,languageLabel,themeFor} from '@/lib/presentation';
import type {Facets,SearchResult} from '@/lib/types';
const EventMap=dynamic(()=>import('./EventMap'),{ssr:false,loading:()=> <div className="map-shell loading">Загружаем карту…</div>});
const emptyFacets:Facets={cities:[],categories:[],languages:[],artists:[],organizers:[],venues:[]};
const icons={music:Music2,business:UsersRound,cinema:Film,theatre:Drama,ideas:Cpu,night:Moon};
function initialFilters(today:string){return {q:'',from:today,to:'',city:'',category:'',language:'',radius_km:'',price_max:'',currency:'EUR',venue:'',artist:'',organizer:'',free:false,sort:'date',bbox:''};}
type Filters=ReturnType<typeof initialFilters>;
export default function Radar({today,initialResult,initialFacets,stagingNotice}:{today:string;initialResult:SearchResult|null;initialFacets:Facets|null;stagingNotice:string}){
 const [filters,setFilters]=useState(()=>initialFilters(today));const [draft,setDraft]=useState(()=>initialFilters(today));
 const [preset,setPreset]=useState('upcoming');const [view,setView]=useState<'list'|'map'>('list');const [result,setResult]=useState(initialResult);
 const [facets,setFacets]=useState(initialFacets||emptyFacets);const [error,setError]=useState('');const [busy,setBusy]=useState(!initialResult);
 const [location,setLocation]=useState<{lat:number;lng:number}|null>(null);const [geoError,setGeoError]=useState('');const [geolocating,setGeolocating]=useState(false);
 const [reload,setReload]=useState(0);const [offset,setOffset]=useState(0);const [dialogOpen,setDialogOpen]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);const catalogue=useRef<HTMLElement>(null);
 const set=useCallback((key:keyof Filters,value:string|boolean)=>{setFilters(f=>({...f,[key]:value}));setOffset(0);},[]);
 const params=useMemo(()=>{const p=new URLSearchParams();for(const [k,v] of Object.entries(filters)){if(v!==''&&v!==false)p.set(k,String(v));}p.set('limit','50');p.set('offset',String(offset));if(location){p.set('lat',String(location.lat));p.set('lng',String(location.lng));}else{p.delete('radius_km');if(filters.sort==='distance')p.set('sort','date');}return p.toString();},[filters,offset,location]);
 const loadedRequest=useRef({params,result:initialResult,reload:0});
 useEffect(()=>{if(loadedRequest.current.result&&loadedRequest.current.params===params&&loadedRequest.current.reload===reload)return;const controller=new AbortController();const timer=setTimeout(async()=>{setBusy(true);setError('');const timeout=setTimeout(()=>controller.abort('timeout'),15000);try{const r=await fetch('/api/v1/events?'+params,{signal:controller.signal,cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.message||'Не удалось загрузить мероприятия.');if(controller.signal.aborted)return;loadedRequest.current={params,result:data,reload};setResult(data);}catch(e){if(!controller.signal.aborted||controller.signal.reason==='timeout'){setError(controller.signal.reason==='timeout'?'Загрузка занимает слишком долго. Попробуйте ещё раз.':e instanceof Error?e.message:'Не удалось загрузить мероприятия.');loadedRequest.current.result=null;setResult(null);}}finally{clearTimeout(timeout);if(!controller.signal.aborted||controller.signal.reason==='timeout')setBusy(false);}},180);return()=>{clearTimeout(timer);controller.abort();};},[params,reload]);
 useEffect(()=>{if(initialFacets&&reload===0)return;const controller=new AbortController();fetch('/api/v1/facets',{signal:controller.signal}).then(async r=>{if(r.ok)setFacets(await r.json());}).catch(()=>{});return()=>controller.abort();},[initialFacets,reload]);
 useEffect(()=>{if(!dialogOpen)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[dialogOpen]);
 const visibleCategories=facets.categories.filter(c=>categoryLabel(c.name)!=='Мероприятие'&&(!initialResult||initialResult.items.some(e=>e.categories.some(k=>k.slug===c.slug))));
 const activeCount=[filters.city,filters.category,filters.language,filters.to,filters.radius_km,filters.price_max,filters.venue,filters.artist,filters.organizer,filters.bbox,filters.free].filter(Boolean).length;
 function showFilters(){setDraft(filters);setDialogOpen(true);dialog.current?.showModal();}
 function closeFilters(){dialog.current?.close();setDialogOpen(false);}
 function reset(){setFilters(initialFilters(today));setDraft(initialFilters(today));setPreset('upcoming');setOffset(0);setLocation(null);setGeoError('');}
 function choosePreset(p:string){setPreset(p);setFilters(f=>({...f,...dateRange(p,today)}));setOffset(0);}
 function locate(){setGeoError('');if(!navigator.geolocation){setGeoError('Геолокация недоступна. Выберите город.');return;}setGeolocating(true);navigator.geolocation.getCurrentPosition(p=>{setLocation({lat:p.coords.latitude,lng:p.coords.longitude});setFilters(f=>({...f,radius_km:f.radius_km||'25',sort:'distance',bbox:''}));setOffset(0);setGeolocating(false);},e=>{setGeoError(e.code===1?'Доступ к местоположению не разрешён. Можно выбрать город.':'Не удалось определить местоположение. Можно выбрать город.');setGeolocating(false);},{enableHighAccuracy:false,timeout:12000,maximumAge:300000});}
 function goTo(v:'list'|'map'){setView(v);catalogue.current?.scrollIntoView({behavior:'smooth',block:'start'});}
 return <>
 <header className="masthead"><div className="header-inner"><Brand/><nav className="desktop-nav" aria-label="Главное меню"><a href="#afisha">Афиша</a><button onClick={()=>goTo('map')}>Карта событий</button></nav><button className="location-button" onClick={locate} disabled={geolocating}><LocateFixed size={17}/><span>{geolocating?'Определяем…':location?'Рядом со мной':'Моё местоположение'}</span><ChevronDown size={14}/></button></div></header>
 {stagingNotice&&<div className="staging">{stagingNotice}</div>}
 <main id="main-content" className="radar-page">
 <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/>СЕВЕРНАЯ ИТАЛИЯ И ШВЕЙЦАРИЯ</div><h1 id="hero-title">Твой город.<br/><span>Твои впечатления.</span></h1><p>От большого концерта до встречи своих.<br className="desktop-break"/> Найди повод выйти из дома.</p><a className="hero-link" href="#afisha">Выбрать событие <ArrowDown size={17}/></a></div><div className="hero-art" aria-hidden="true"><div className="orbit-glow"/><div className="orbit-sphere"><div className="sphere-ring ring-one"/><div className="sphere-ring ring-two"/><div className="sphere-ring ring-three"/><div className="sphere-ring ring-four"/><div className="sphere-core"><Sparkles size={48}/></div></div><div className="floating-ticket ticket-one"><Music2 size={21}/><span>ХОРОШИЙ ВЕЧЕР</span><ArrowUpRight size={20}/></div><div className="floating-ticket ticket-two"><Ticket size={22}/><span>ТВОЙ ВХОД<br/><strong>В НОВЫЕ ВСТРЕЧИ</strong></span></div><span className="orbit-dot dot-one"/><span className="orbit-dot dot-two"/><span className="orbit-cross">✳</span></div></section>
 <section id="afisha" ref={catalogue} className="catalogue" aria-labelledby="catalogue-title">
 <div className="catalogue-head"><div><p className="section-kicker">БЛИЖЕ, ЧЕМ КАЖЕТСЯ</p><h2 id="catalogue-title">Афиша событий<span className="heading-dot">.</span></h2></div><span className="catalogue-region"><MapPin size={15}/>Комо · Милан · Лугано · Цюрих</span></div>
 <div className="search-row"><label className="search-box"><Search size={20}/><input aria-label="Поиск мероприятий" placeholder="Куда хочется пойти?" value={filters.q} onChange={e=>set('q',e.target.value)}/>{filters.q&&<button aria-label="Очистить поиск" onClick={()=>set('q','')}><X size={17}/></button>}</label><div className="city-select"><MapPin size={17}/><select aria-label="Город" value={filters.city} onChange={e=>set('city',e.target.value)}><option value="">Все города</option>{facets.cities.map(c=><option key={c} value={c}>{cityLabel(c)}</option>)}</select><ChevronDown size={14}/></div><button className="filter-button" onClick={showFilters} aria-haspopup="dialog"><SlidersHorizontal size={18}/><span>Фильтры</span>{activeCount>0&&<b>{activeCount}</b>}</button></div>
 <div className="quick-row"><div className="date-presets" role="group" aria-label="Период"><button className={preset==='upcoming'?'selected':''} aria-pressed={preset==='upcoming'} onClick={()=>choosePreset('upcoming')}>Ближайшие</button><button className={preset==='today'?'selected':''} aria-pressed={preset==='today'} onClick={()=>choosePreset('today')}>Сегодня</button><button className={preset==='tomorrow'?'selected':''} aria-pressed={preset==='tomorrow'} onClick={()=>choosePreset('tomorrow')}>Завтра</button><button className={preset==='weekend'?'selected':''} aria-pressed={preset==='weekend'} onClick={()=>choosePreset('weekend')}>Выходные</button></div><button className={'russian-toggle '+(filters.language==='ru'?'selected':'')} aria-pressed={filters.language==='ru'} onClick={()=>set('language',filters.language==='ru'?'':'ru')}>На русском <span className="toggle-track"><i/></span></button></div>
 <div className="category-strip" role="group" aria-label="Категории мероприятий"><button className={!filters.category?'selected':''} aria-pressed={!filters.category} onClick={()=>set('category','')}><Sparkles size={16}/>Все события</button>{visibleCategories.map(c=>{const Icon=icons[themeFor(c.name)];return <button key={c.slug} className={filters.category===c.slug?'selected':''} aria-pressed={filters.category===c.slug} onClick={()=>set('category',filters.category===c.slug?'':c.slug||'')}><Icon size={16}/>{categoryLabel(c.name)}</button>;})}</div>
 {geoError&&<div className="inline-notice" role="alert"><LocateFixed size={18}/><p>{geoError}</p><button aria-label="Закрыть сообщение" onClick={()=>setGeoError('')}><X size={18}/></button></div>}
 <div className="results-toolbar"><div className="result-count" aria-live="polite"><span className={busy?'live-dot is-busy':'live-dot'}/>{busy?'Обновляем афишу…':result?eventCount(result.total):'Афиша'}{activeCount>0&&<button className="text-button" onClick={reset}>Сбросить</button>}</div><div className="result-controls"><select aria-label="Сортировка" value={filters.sort} onChange={e=>set('sort',e.target.value)}><option value="date">По дате</option><option value="newest">Сначала новые</option><option value="distance" disabled={!location}>По расстоянию</option></select><div className="view-switch" role="group" aria-label="Вид мероприятий"><button aria-label="Список" aria-pressed={view==='list'} className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={18}/><span>Список</span></button><button aria-label="Карта" aria-pressed={view==='map'} className={view==='map'?'active':''} onClick={()=>setView('map')}><MapIcon size={18}/><span>Карта</span></button></div></div></div>
 {location&&<div className="area-filter"><LocateFixed size={15}/>В радиусе {filters.radius_km||'любого количества'} км <button onClick={()=>{setLocation(null);setFilters(f=>({...f,radius_km:'',sort:'date'}));setOffset(0);}}>Убрать <X size={14}/></button></div>}
 {filters.bbox&&<div className="area-filter"><MapIcon size={15}/>Выбрана область карты<button onClick={()=>set('bbox','')}>Убрать <X size={14}/></button></div>}
 <section className="results" aria-label="Результаты поиска" aria-busy={busy}>
 {error?<div className="empty-state" role="alert"><RefreshCw size={32}/><h3>Афиша временно недоступна</h3><p>{error}</p><button className="primary-button" onClick={()=>setReload(n=>n+1)}>Попробовать ещё раз <RefreshCw size={16}/></button></div>:view==='map'?<><EventMap events={result?.items||[]} location={location} onBounds={b=>set('bbox',b)}/>{result&&<p className="map-note"><ShieldCheck size={15}/>{result.mapped} из {result.total} событий имеют проверенные координаты. Остальные доступны в списке.</p>}</>:result?.items.length?<div className={'event-grid '+(busy?'updating':'')}>{result.items.map((e,i)=><EventCard key={e.occurrence_id} event={e} index={i}/>)}</div>:busy?<div className="skeleton-grid" aria-label="Загрузка мероприятий">{[0,1,2,3,4,5].map(n=><div className="skeleton-card" key={n}><div/><i/><i/><i/></div>)}</div>:<div className="empty-state"><Search size={32}/><h3>Пока ничего не нашлось</h3><p>Попробуйте другие даты, город или радиус. Это результат выбранных фильтров, а не полный список событий.</p><button className="primary-button" onClick={reset}>Показать ближайшие события <ArrowUpRight size={17}/></button></div>}
 </section>
 {result&&result.total>50&&<nav className="pagination" aria-label="Страницы результатов"><button disabled={offset===0||busy} onClick={()=>setOffset(Math.max(0,offset-50))}>Назад</button><span>{offset+1} - {Math.min(offset+50,result.total)} из {result.total}</span><button disabled={offset+50>=result.total||busy} onClick={()=>setOffset(offset+50)}>Далее</button></nav>}
 <div className="source-note"><ShieldCheck size={17}/><p>У каждого события есть источник. Даты и условия входа проверяйте перед поездкой.</p></div>
 </section></main>
 <nav className="mobile-dock" aria-label="Мобильное меню"><button className={view==='list'?'active':''} aria-current={view==='list'?'page':undefined} onClick={()=>goTo('list')}><Ticket size={20}/><span>Афиша</span></button><button className={view==='map'?'active':''} aria-current={view==='map'?'page':undefined} onClick={()=>goTo('map')}><MapIcon size={20}/><span>Карта</span></button><button onClick={showFilters} aria-haspopup="dialog"><SlidersHorizontal size={20}/><span>Фильтры{activeCount>0?` · ${activeCount}`:''}</span></button><button onClick={locate} disabled={geolocating}><LocateFixed size={20}/><span>{geolocating?'Ищем…':'Рядом'}</span></button></nav>
 <dialog ref={dialog} className="filter-dialog" aria-labelledby="filter-title" onCancel={()=>setDialogOpen(false)} onClose={()=>setDialogOpen(false)} onClick={e=>{if(e.target===dialog.current){const r=dialog.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeFilters();}}}>
 <div className="dialog-handle" aria-hidden="true"/><div className="dialog-heading"><div><p className="section-kicker">ТВОЙ ВЫБОР</p><h2 id="filter-title">Настроить афишу</h2></div><button className="icon-button" autoFocus aria-label="Закрыть фильтры" onClick={closeFilters}><X size={21}/></button></div>
 <form onSubmit={e=>{e.preventDefault();setFilters(draft);setPreset(draft.from===today&&!draft.to?'upcoming':'custom');setOffset(0);closeFilters();}}>
 <div className="dialog-fields"><div className="field-row"><label>С даты<input type="date" value={draft.from} onChange={e=>setDraft(d=>({...d,from:e.target.value}))}/></label><label>По дату<input type="date" value={draft.to} min={draft.from} onChange={e=>setDraft(d=>({...d,to:e.target.value}))}/></label></div>
 <label>Город<select value={draft.city} onChange={e=>setDraft(d=>({...d,city:e.target.value}))}><option value="">Все города</option>{facets.cities.map(c=><option value={c} key={c}>{cityLabel(c)}</option>)}</select></label>
 <div className="field-row"><label>Категория<select value={draft.category} onChange={e=>setDraft(d=>({...d,category:e.target.value}))}><option value="">Все категории</option>{facets.categories.filter(c=>categoryLabel(c.name)!=='Мероприятие').map(c=><option value={c.slug} key={c.slug}>{categoryLabel(c.name)}</option>)}</select></label><label>Язык<select value={draft.language} onChange={e=>setDraft(d=>({...d,language:e.target.value}))}><option value="">Любой язык</option>{facets.languages.map(l=><option value={l.code} key={l.code}>{languageLabel(l.code)}</option>)}</select></label></div>
 <label>Радиус поиска, км<select value={draft.radius_km} disabled={!location} onChange={e=>setDraft(d=>({...d,radius_km:e.target.value}))}><option value="">Любой радиус</option>{[1,5,10,25,30,50,100,250].map(n=><option key={n} value={n}>{n} км</option>)}</select><small>{location?'События без проверенных координат не входят в поиск по радиусу.':'Чтобы выбрать радиус, сначала нажмите «Рядом».'}</small></label>
 <div className="field-row"><label>Цена до<input type="number" min="0" placeholder="Любая" value={draft.price_max} onChange={e=>setDraft(d=>({...d,price_max:e.target.value}))}/></label><label>Валюта<select value={draft.currency} onChange={e=>setDraft(d=>({...d,currency:e.target.value}))}><option value="EUR">Евро</option><option value="CHF">Швейцарский франк</option></select></label></div>
 <label className="checkbox"><input type="checkbox" checked={draft.free} onChange={e=>setDraft(d=>({...d,free:e.target.checked}))}/><span>Только бесплатные события</span></label>
 <details className="more-filters"><summary>Площадка, артист, организатор</summary>{(['venue','artist','organizer'] as const).map((key,i)=><label key={key}>{['Площадка','Артист','Организатор'][i]}<select value={draft[key]} onChange={e=>setDraft(d=>({...d,[key]:e.target.value}))}><option value="">Все</option>{facets[({venue:'venues',artist:'artists',organizer:'organizers'} as const)[key]].map(s=><option key={s}>{s}</option>)}</select></label>)}</details>
 </div><div className="dialog-actions"><button type="button" className="secondary-button" onClick={()=>setDraft(initialFilters(today))}>Очистить</button><button className="primary-button" type="submit">Показать события <ArrowUpRight size={18}/></button></div></form></dialog>
 </>;
}
